# Generated by Django 6.0.1 on 2026-05-30 06:49

import apps.content.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False, help_text='Notes are free for everyone.')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Price to unlock this chapter's notes (ignored when free).", max_digits=8)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MBBSYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(help_text='1, 2, 3, 4 …', unique=True)),
                ('title', models.CharField(help_text='e.g. "MBBS 2nd Year"', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MBBS year',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(blank=True, max_length=32)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional custom thumbnail; otherwise the YouTube thumbnail is used.', null=True, upload_to='lectures/')),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. "12:34"', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='content.chapter')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.content.models.note_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='pdf', max_length=10)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='content.chapter')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='subjects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional discounted price to unlock the entire subject's notes.", max_digits=8, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.mbbsyear')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price to unlock all chapters in this unit.', max_digits=8, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('subject', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.unit'),
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('lectures', 'YouTube Lectures'), ('notes', 'Complete Notes'), ('one_shots', 'One Shots')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional label override.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.subject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('subject', 'kind')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('unit', 'slug')},
        ),
    ]
