# Generated by Django 6.0.1 on 2026-06-12 15:32

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='compressed_key',
            field=models.CharField(blank=True, default='', help_text='Storage key of the compressed rendition (blank = none).', max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='compressed_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='file_version',
            field=models.CharField(blank=True, default='', help_text='Changes on every (re)upload; versions keys + viewer caches.', max_length=40),
        ),
        migrations.AddField(
            model_name='note',
            name='original_key',
            field=models.CharField(blank=True, default='', help_text='Storage key of the untouched uploaded file.', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.content.models.note_upload_path),
        ),
    ]
