# Generated by Django 6.0.1 on 2026-06-13 16:10

from django.db import migrations, models


def set_bundle_pricing_modes(apps, schema_editor):
    """Preserve current behaviour for existing data:
      - rows with a custom price set today  -> 'custom'
      - rows with no price (sold at the sum) -> 'sum' (the field default)
    Nothing becomes "not sold" automatically; the admin opts into that per item.
    """
    for model_name in ("Subject", "Unit"):
        Model = apps.get_model("content", model_name)
        Model.objects.filter(bundle_price__isnull=False).update(bundle_pricing="custom")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_note_compressed_key_note_compressed_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bundle_pricing',
            field=models.CharField(choices=[('sum', 'Sum of chapter prices'), ('custom', 'Custom price'), ('none', 'Not sold as a bundle (chapters only)')], default='sum', help_text='How the whole-subject price is set (sum of chapters, custom, or not sold).', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='bundle_pricing',
            field=models.CharField(choices=[('sum', 'Sum of chapter prices'), ('custom', 'Custom price'), ('none', 'Not sold as a bundle (chapters only)')], default='sum', help_text='How the whole-unit price is set (sum of chapters, custom, or not sold).', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Custom price to unlock the entire subject's notes (used only with the custom option).", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price to unlock all chapters in this unit (used only with the custom option).', max_digits=8, null=True),
        ),
        migrations.RunPython(set_bundle_pricing_modes, noop),
    ]
