# Generated by Django 6.0.1 on 2026-06-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_bundle_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Heading shown on the dashboard, e.g. "How to study effectively".', max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short blurb shown under the heading.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'general video section',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. "12:34"', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.generalvideosection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
