# Generated by Django 6.0.1 on 2026-06-21 12:08
#
# Moves the priced leaf down from Chapter to Note and turns the Chapter into a
# bundle (like Unit/Subject). Operation order is deliberate: add the new fields,
# COPY each existing chapter's `price` into a CUSTOM `bundle_price` (so every
# current chapter stays purchasable at exactly its old price and all unit/subject
# SUM roll-ups are unchanged), and only THEN drop the old `price` column.

from decimal import Decimal

from django.db import migrations, models


def preserve_chapter_prices(apps, schema_editor):
    """Existing chapters keep their current whole-chapter price as a CUSTOM bundle
    price. Free or ₹0 chapters keep the default 'sum' mode (price now lives on the
    notes). This guarantees no existing content changes price or loses access."""
    Chapter = apps.get_model("content", "Chapter")
    Chapter.objects.filter(is_free=False, price__gt=0).update(
        bundle_pricing="custom", bundle_price=models.F("price")
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_general_video_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Custom price to unlock all of this chapter's notes (used only with the custom option).", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='bundle_pricing',
            field=models.CharField(choices=[('sum', "Sum of contents' prices"), ('custom', 'Custom price'), ('none', 'Not sold as a bundle (contents only)')], default='sum', help_text='How the whole-chapter price is set (sum of notes, custom, or not sold).', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free for everyone (no payment needed).'),
        ),
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price to buy this note on its own (0 = only sold within the chapter).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False, help_text='All notes in this chapter are free for everyone.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bundle_pricing',
            field=models.CharField(choices=[('sum', "Sum of contents' prices"), ('custom', 'Custom price'), ('none', 'Not sold as a bundle (contents only)')], default='sum', help_text='How the whole-subject price is set (sum of chapters, custom, or not sold).', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bundle_pricing',
            field=models.CharField(choices=[('sum', "Sum of contents' prices"), ('custom', 'Custom price'), ('none', 'Not sold as a bundle (contents only)')], default='sum', help_text='How the whole-unit price is set (sum of chapters, custom, or not sold).', max_length=10),
        ),
        # Copy old per-chapter prices into the new bundle field BEFORE dropping it.
        migrations.RunPython(preserve_chapter_prices, noop),
        migrations.RemoveField(
            model_name='chapter',
            name='price',
        ),
    ]
