# Generated by Django 6.0.1 on 2026-06-05 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='page',
            field=models.PositiveIntegerField(blank=True, help_text='1-based page for paginated notes; null for whole-object bookmarks.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'content_type', 'object_id', 'page')},
        ),
    ]
