# Generated by Django 6.0.1 on 2026-06-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_bookmark_unique_together_bookmark_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
