"""Tests for the general (dashboard) videos feature.

Three-level tree: GeneralVideoHeading → GeneralVideoSection (playlist) →
GeneralVideo. Covers the public dashboard API (published-only filtering, nesting,
no link to the year/subject tree), the admin CRUD viewsets (admin-only), and the
playlist importer (happy path, duplicate skipping, unavailable videos, missing
section, admin-only access). No real network calls — the YouTube layer is
mocked, exactly like the chapter importer tests.
"""

from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings
from rest_framework.test import APIClient

from .models import GeneralVideo, GeneralVideoHeading, GeneralVideoSection

User = get_user_model()

LIST_URL = "/api/v1/general-videos/"
IMPORT_URL = "/api/v1/admin/general-videos/import-playlist/"
HEADINGS_URL = "/api/v1/admin/general-headings/"
SECTIONS_URL = "/api/v1/admin/general-sections/"
VIDEOS_URL = "/api/v1/admin/general-videos/"


def video(vid, title=None, description="desc", duration="12:34", unavailable=False):
    return {
        "video_id": vid,
        "title": title or f"Video {vid}",
        "description": description,
        "duration": duration,
        "unavailable": unavailable,
    }


class GeneralVideoModelTests(TestCase):
    def test_slugs_autogenerated_and_unique(self):
        h1 = GeneralVideoHeading.objects.create(title="The Academic Edge")
        h2 = GeneralVideoHeading.objects.create(title="The Academic Edge")
        self.assertEqual(h1.slug, "the-academic-edge")
        self.assertNotEqual(h2.slug, h1.slug)

        s = GeneralVideoSection.objects.create(heading=h1, title="How to study")
        self.assertEqual(s.slug, "how-to-study")

    def test_video_id_and_thumbnail_derived_from_url(self):
        h = GeneralVideoHeading.objects.create(title="Tips")
        s = GeneralVideoSection.objects.create(heading=h, title="Study")
        v = GeneralVideo.objects.create(
            section=s, title="A", youtube_url="https://youtu.be/abcdefghijk"
        )
        self.assertEqual(v.youtube_video_id, "abcdefghijk")
        self.assertIn("abcdefghijk", v.thumbnail_url)


class GeneralVideoPublicApiTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.heading = GeneralVideoHeading.objects.create(title="The Academic Edge", order=0)
        self.section = GeneralVideoSection.objects.create(
            heading=self.heading, title="How to study", order=0
        )
        GeneralVideo.objects.create(
            section=self.section, title="Pub", youtube_url="https://youtu.be/aaaaaaaaaaa",
            order=0, is_published=True,
        )
        GeneralVideo.objects.create(
            section=self.section, title="Hidden", youtube_url="https://youtu.be/bbbbbbbbbbb",
            order=1, is_published=False,
        )

    def test_lists_headings_with_published_playlists_and_videos(self):
        res = self.client.get(LIST_URL)
        self.assertEqual(res.status_code, 200)
        self.assertEqual(len(res.data), 1)
        heading = res.data[0]
        self.assertEqual(heading["title"], "The Academic Edge")
        self.assertEqual(len(heading["playlists"]), 1)
        titles = [v["title"] for v in heading["playlists"][0]["videos"]]
        self.assertEqual(titles, ["Pub"])  # hidden video excluded

    def test_unpublished_heading_is_hidden(self):
        self.heading.is_published = False
        self.heading.save()
        res = self.client.get(LIST_URL)
        self.assertEqual(res.data, [])

    def test_unpublished_playlist_excluded(self):
        self.section.is_published = False
        self.section.save()
        res = self.client.get(LIST_URL)
        self.assertEqual(res.data[0]["playlists"], [])

    def test_open_to_anonymous(self):
        res = APIClient().get(LIST_URL)
        self.assertEqual(res.status_code, 200)


@override_settings(YOUTUBE_API_KEY="test-key")
class GeneralVideoAdminTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.student = User.objects.create_user(
            email="s@example.com", full_name="Stu", password="Pass@1234"
        )
        self.admin = User.objects.create_superuser(
            email="admin@example.com", full_name="Admin", password="Pass@1234"
        )
        self.heading = GeneralVideoHeading.objects.create(title="The Academic Edge")
        self.section = GeneralVideoSection.objects.create(heading=self.heading, title="How to study")

    # --- Heading CRUD ---
    def test_admin_can_crud_heading(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(HEADINGS_URL, {"title": "Exam Prep"}, format="json")
        self.assertEqual(res.status_code, 201)
        hid = res.data["id"]
        self.assertEqual(res.data["playlist_count"], 0)

        res = self.client.patch(f"{HEADINGS_URL}{hid}/", {"is_published": False}, format="json")
        self.assertEqual(res.status_code, 200)
        self.assertFalse(res.data["is_published"])

        res = self.client.delete(f"{HEADINGS_URL}{hid}/")
        self.assertEqual(res.status_code, 204)
        self.assertFalse(GeneralVideoHeading.objects.filter(pk=hid).exists())

    def test_deleting_heading_cascades_to_playlists(self):
        self.client.force_authenticate(self.admin)
        self.client.delete(f"{HEADINGS_URL}{self.heading.id}/")
        self.assertFalse(GeneralVideoSection.objects.filter(pk=self.section.id).exists())

    # --- Section (playlist) CRUD ---
    def test_admin_can_create_section_under_heading(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(SECTIONS_URL, {
            "heading": self.heading.id, "title": "Timetables",
        }, format="json")
        self.assertEqual(res.status_code, 201)
        self.assertEqual(res.data["heading"], self.heading.id)

    def test_sections_filterable_by_heading(self):
        self.client.force_authenticate(self.admin)
        other = GeneralVideoHeading.objects.create(title="Other")
        GeneralVideoSection.objects.create(heading=other, title="Elsewhere")
        res = self.client.get(SECTIONS_URL, {"heading": self.heading.id})
        self.assertEqual(len(res.data), 1)
        self.assertEqual(res.data[0]["title"], "How to study")

    # --- Video CRUD ---
    def test_admin_can_crud_video_and_edit_fields(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(VIDEOS_URL, {
            "section": self.section.id,
            "title": "Intro",
            "youtube_url": "https://youtu.be/abcdefghijk",
        }, format="json")
        self.assertEqual(res.status_code, 201)
        vid = res.data["id"]
        self.assertEqual(res.data["youtube_video_id"], "abcdefghijk")

        res = self.client.patch(f"{VIDEOS_URL}{vid}/", {
            "description": "Edited", "duration": "5:00", "order": 3, "is_published": False,
        }, format="json")
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.data["description"], "Edited")
        self.assertFalse(res.data["is_published"])

    def test_videos_filterable_by_section(self):
        self.client.force_authenticate(self.admin)
        other = GeneralVideoSection.objects.create(heading=self.heading, title="Other")
        GeneralVideo.objects.create(section=self.section, title="A", youtube_url="https://youtu.be/aaaaaaaaaaa")
        GeneralVideo.objects.create(section=other, title="B", youtube_url="https://youtu.be/bbbbbbbbbbb")
        res = self.client.get(VIDEOS_URL, {"section": self.section.id})
        self.assertEqual(len(res.data), 1)
        self.assertEqual(res.data[0]["title"], "A")

    def test_crud_requires_admin(self):
        self.client.force_authenticate(self.student)
        self.assertEqual(self.client.get(HEADINGS_URL).status_code, 403)
        self.assertEqual(self.client.post(SECTIONS_URL, {"heading": self.heading.id, "title": "X"}, format="json").status_code, 403)

    # --- Playlist import (into a section) ---
    def test_import_creates_unpublished_editable_videos(self):
        self.client.force_authenticate(self.admin)
        fake = [video("aaa"), video("bbb")]
        with patch("apps.content.admin_views.fetch_playlist_videos", return_value=fake):
            res = self.client.post(IMPORT_URL, {
                "section": self.section.id,
                "playlist_url": "https://www.youtube.com/playlist?list=PLx",
            })
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.data["imported"], 2)
        v = self.section.videos.get(youtube_video_id="aaa")
        self.assertEqual(v.youtube_url, "https://www.youtube.com/watch?v=aaa")
        self.assertFalse(v.is_published)  # imports default to unpublished
        self.assertGreater(v.order, 0)

    def test_import_skips_duplicates_in_same_section(self):
        self.client.force_authenticate(self.admin)
        GeneralVideo.objects.create(
            section=self.section, title="Existing",
            youtube_url="https://www.youtube.com/watch?v=aaa",
            youtube_video_id="aaa", order=5,
        )
        fake = [video("aaa"), video("ccc")]
        with patch("apps.content.admin_views.fetch_playlist_videos", return_value=fake):
            res = self.client.post(IMPORT_URL, {"section": self.section.id, "playlist_url": "PLxxxxxxxxxx"})
        self.assertEqual(res.data["imported"], 1)
        self.assertEqual(res.data["skipped"], 1)
        self.assertEqual(self.section.videos.get(youtube_video_id="ccc").order, 6)

    def test_import_reports_unavailable_videos(self):
        self.client.force_authenticate(self.admin)
        fake = [video("ok1"), video("priv", title="Private video", unavailable=True)]
        with patch("apps.content.admin_views.fetch_playlist_videos", return_value=fake):
            res = self.client.post(IMPORT_URL, {"section": self.section.id, "playlist_url": "PLxxxxxxxxxx"})
        self.assertEqual(res.data["imported"], 1)
        self.assertEqual(res.data["failed"], 1)

    def test_import_invalid_url(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(IMPORT_URL, {"section": self.section.id, "playlist_url": "https://example.com/nope"})
        self.assertEqual(res.status_code, 400)
        self.assertEqual(self.section.videos.count(), 0)

    def test_import_missing_section(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(IMPORT_URL, {"section": 99999, "playlist_url": "PLxxxxxxxxxx"})
        self.assertEqual(res.status_code, 404)

    @override_settings(YOUTUBE_API_KEY="")
    def test_import_missing_api_key_graceful(self):
        self.client.force_authenticate(self.admin)
        res = self.client.post(IMPORT_URL, {
            "section": self.section.id,
            "playlist_url": "https://www.youtube.com/playlist?list=PLx",
        })
        self.assertEqual(res.status_code, 400)
        self.assertIn("not configured", res.data["detail"])

    def test_import_requires_admin(self):
        self.client.force_authenticate(self.student)
        res = self.client.post(IMPORT_URL, {"section": self.section.id, "playlist_url": "PLxxxxxxxxxx"})
        self.assertEqual(res.status_code, 403)
