# Generated by Django 6.0.1 on 2026-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='The Digital Product Mart', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Watch chapter-wise lectures and study clean, protected notes — a trusted, focused space made for medical students.', max_length=300)),
                ('byline', models.CharField(default='Digikart', max_length=120)),
                ('owner_name', models.CharField(default='Digikart', max_length=120)),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@digikart')),
                ('instagram_url', models.URLField(blank=True, default='https://youtube.com/@digikart')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/digikart')),
                ('help_text', models.TextField(blank=True, default="Have a doubt or need support? Reach out and we'll get back to you.")),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('meta_description', models.CharField(blank=True, default='Digikart â a digital product mart: list and sell files, notes, videos, links and bundles.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
    ]
