# Generated by Django 6.0.1 on 2026-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_homepage_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_us',
            field=models.TextField(blank=True, help_text='Content of the About Us page.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Content of the Disclaimer page.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_tagline',
            field=models.TextField(blank=True, default='Enzyme fueled path to your MBBS journey — chapter-wise lectures and protected, premium notes.', help_text='The blurb under the footer logo.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Content of the Privacy Policy page.'),
        ),
    ]
