# Generated by Django 6.0.1 on 2026-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_sitecontent_about_us_sitecontent_disclaimer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='meta_description',
            field=models.CharField(blank=True, default='Digikart â a digital product mart: list and sell files, notes, videos, links and bundles.', max_length=200),
        ),
    ]
