# Generated by Django 6.0.1 on 2026-06-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_alter_sitecontent_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='contact_phone',
        ),
    ]
