# Generated by Django 6.0.1 on 2026-07-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_remove_sitecontent_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='youtube_url',
        ),
    ]
