# Generated by Django 6.0.1 on 2026-07-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_remove_sitecontent_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='byline',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='footer_tagline',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight1_desc',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight1_title',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight2_desc',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight2_title',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight3_desc',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='highlight3_title',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='owner_name',
        ),
    ]
