# Generated by Django 6.0.1 on 2026-08-08 08:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bundles/')),
                ('pricing', models.CharField(choices=[('sum', "Sum of contents' prices"), ('custom', 'Custom price')], default='sum', max_length=10)),
                ('custom_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Used only when pricing is 'custom'.", max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Off = not listed for sale, but existing buyers keep their access.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('youtube_url', models.URLField(blank=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=32)),
                ('is_free', models.BooleanField(default=False, help_text='Free for everyone (no payment needed).')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price to buy this product on its own (0 = only sold inside a bundle).', max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('delivery', models.CharField(choices=[('protected', 'Protected viewer (watermarked, no download)'), ('download', 'Direct download')], default='download', max_length=12)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('archive', 'Archive (zip/rar)'), ('document', 'Document'), ('other', 'Other')], default='pdf', max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('original_key', models.CharField(blank=True, default='', help_text='Storage key of the untouched uploaded file.', max_length=500)),
                ('compressed_key', models.CharField(blank=True, default='', help_text='Storage key of the compressed rendition (blank = none).', max_length=500)),
                ('file_version', models.CharField(blank=True, default='', help_text='Changes on every (re)upload; versions keys + viewer caches.', max_length=40)),
                ('legacy_file', models.FileField(blank=True, help_text='Pre-R2 rows migrated from Note.file; served as a single rendition.', max_length=500, upload_to='')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('compressed_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.bundle')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='catalog_bun_content_b921c3_idx')],
                'unique_together': {('bundle', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='BundleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.bundle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memberships', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'bundle'], name='catalog_bun_product_875419_idx')],
                'unique_together': {('bundle', 'product')},
            },
        ),
    ]
