# Generated by Django 6.0.1 on 2026-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='legacy_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='productfile',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfile',
            name='legacy_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='bundle',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_kind', 'legacy_id'), name='catalog_bundle_unique_legacy_ref'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_kind', 'legacy_id'), name='catalog_category_unique_legacy_ref'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_kind', 'legacy_id'), name='catalog_product_unique_legacy_ref'),
        ),
        migrations.AddConstraint(
            model_name='productfile',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_kind', 'legacy_id'), name='catalog_productfile_unique_legacy_ref'),
        ),
    ]
