# Generated by Django 6.0.1 on 2026-05-30 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, optional +, 7–20 chars).', regex='^\\+?[0-9\\s\\-]{7,20}$')], verbose_name='phone number'),
        ),
    ]
