# Generated by Django 6.0.1 on 2026-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
