# Generated by Django 6.0.1 on 2026-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=2, verbose_name='country'),
        ),
    ]
