# Generated by Django 6.0.1 on 2026-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='Free text, e.g. "2nd year medical student".', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.CharField(blank=True, help_text='College, studio, company — whatever fits.', max_length=200),
        ),
    ]
