/* Field schemas that drive the admin forms for each resource. */

const comingSoon = { name: "is_coming_soon", label: "Mark as Coming Soon", type: "toggle" };
const published = {
  name: "is_published",
  label: "Published (visible to students)",
  type: "toggle",
  hint: "Turn off to hide completely.",
};
const order = { name: "order", label: "Display order", type: "number", hint: "Lower shows first." };

export const SCHEMAS = {
  years: [
    { name: "number", label: "Year number", type: "number", required: true, hint: "1, 2, 3, 4…" },
    { name: "title", label: "Title", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    order,
    comingSoon,
    published,
  ],
  subjects: [
    { name: "name", label: "Subject name", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    {
      name: "bundle_pricing",
      label: "Sell the whole subject as a bundle?",
      type: "select",
      options: [
        { value: "sum", label: "Yes — price = sum of its chapters" },
        { value: "custom", label: "Yes — at a custom price" },
        { value: "none", label: "No — sell chapters individually only" },
      ],
      hint: "Choose how (or whether) students can unlock the entire subject in one purchase.",
    },
    {
      name: "bundle_price",
      label: "Custom whole-subject price (₹)",
      type: "price",
      showIf: (v) => v.bundle_pricing === "custom",
      hint: "Used only with the custom option.",
    },
    order,
    comingSoon,
    published,
  ],
  sections: [
    {
      name: "kind",
      label: "Section",
      type: "select",
      options: [
        { value: "lectures", label: "YouTube Lectures" },
        { value: "notes", label: "Complete Notes" },
        { value: "one_shots", label: "One Shots" },
      ],
    },
    { name: "title", label: "Label override (optional)", type: "text" },
    order,
    comingSoon,
    published,
  ],
  units: [
    { name: "name", label: "Unit name", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    {
      name: "bundle_pricing",
      label: "Sell the whole unit as a bundle?",
      type: "select",
      options: [
        { value: "sum", label: "Yes — price = sum of its chapters" },
        { value: "custom", label: "Yes — at a custom price" },
        { value: "none", label: "No — sell chapters individually only" },
      ],
      hint: "Choose how (or whether) students can unlock the entire unit in one purchase.",
    },
    {
      name: "bundle_price",
      label: "Custom whole-unit price (₹)",
      type: "price",
      showIf: (v) => v.bundle_pricing === "custom",
      hint: "Used only with the custom option.",
    },
    order,
    comingSoon,
    published,
  ],
  chapters: [
    { name: "name", label: "Chapter name", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "is_free", label: "All notes free (no payment needed)", type: "toggle" },
    {
      name: "bundle_pricing",
      label: "Sell the whole chapter as a bundle?",
      type: "select",
      options: [
        { value: "sum", label: "Yes — price = sum of its notes" },
        { value: "custom", label: "Yes — at a custom price" },
        { value: "none", label: "No — sell notes individually only" },
      ],
      showIf: (v) => !v.is_free,
      hint: "Choose how (or whether) students can unlock all of this chapter's notes in one purchase.",
    },
    {
      name: "bundle_price",
      label: "Custom whole-chapter price (₹)",
      type: "price",
      showIf: (v) => !v.is_free && v.bundle_pricing === "custom",
      hint: "Used only with the custom option.",
    },
    order,
    comingSoon,
    published,
  ],
  lectures: [
    { name: "title", label: "Lecture title", type: "text", required: true },
    { name: "youtube_url", label: "YouTube URL", type: "url", required: true, hint: "Full watch/share link." },
    { name: "description", label: "Description", type: "textarea" },
    { name: "duration", label: "Duration", type: "text", hint: 'e.g. "12:34"' },
    order,
    { name: "is_published", label: "Published", type: "toggle" },
  ],
  "general-headings": [
    { name: "title", label: "Heading", type: "text", required: true, hint: 'Top-level dashboard heading, e.g. "The Academic Edge".' },
    order,
    published,
  ],
  "general-sections": [
    { name: "title", label: "Subheading", type: "text", required: true, hint: 'Playlist card title, e.g. "How to study effectively".' },
    { name: "description", label: "Description (optional)", type: "textarea", hint: "Short blurb shown on the card." },
    order,
    published,
  ],
  "general-videos": [
    { name: "title", label: "Video title", type: "text", required: true },
    { name: "youtube_url", label: "YouTube URL", type: "url", required: true, hint: "Full watch/share link." },
    { name: "description", label: "Description", type: "textarea" },
    { name: "duration", label: "Duration", type: "text", hint: 'e.g. "12:34"' },
    order,
    { name: "is_published", label: "Published", type: "toggle" },
  ],
  announcements: [
    { name: "title", label: "Title", type: "text", required: true },
    { name: "body", label: "Message", type: "textarea" },
    { name: "link_url", label: "Link URL (optional)", type: "url" },
    { name: "link_label", label: "Link label (optional)", type: "text" },
    order,
    { name: "is_active", label: "Active (show on site)", type: "toggle" },
  ],
  coupons: [
    { name: "code", label: "Coupon code", type: "text", required: true, hint: "e.g. WELCOME20 — saved trimmed & uppercase." },
    {
      name: "kind",
      label: "Discount type",
      type: "select",
      options: [
        { value: "percent", label: "Percentage off (%)" },
        { value: "flat", label: "Fixed amount off (₹)" },
      ],
    },
    {
      name: "value",
      label: "Discount value",
      type: "number",
      required: true,
      hint: "1–100 for a percentage, or the ₹ amount for a fixed discount.",
    },
    { name: "max_uses", label: "Maximum total uses", type: "number", hint: "Leave blank for unlimited." },
    { name: "min_amount", label: "Minimum purchase (₹)", type: "price", hint: "Optional — leave 0 for no minimum." },
    { name: "valid_from", label: "Starts at (optional)", type: "datetime", hint: "Leave blank to start immediately." },
    { name: "valid_to", label: "Expires at (optional)", type: "datetime", hint: "Leave blank for no expiry." },
    { name: "is_active", label: "Active", type: "toggle", default: true, hint: "Turn off to deactivate without deleting." },
  ],
  notes: [
    { name: "title", label: "Note title", type: "text", required: true },
    { name: "file", label: "File (PDF)", type: "file", accept: "application/pdf", hint: "PDF for now; video/image supported later." },
    {
      name: "file_type",
      label: "File type",
      type: "select",
      options: [
        { value: "pdf", label: "PDF" },
        { value: "video", label: "Video" },
        { value: "image", label: "Image" },
        { value: "other", label: "Other" },
      ],
    },
    { name: "is_free", label: "Free note (no payment needed)", type: "toggle" },
    {
      name: "price",
      label: "Note price (₹)",
      type: "price",
      showIf: (v) => !v.is_free,
      hint: "Price to buy this note on its own. Leave 0 to sell it only as part of the chapter.",
    },
    order,
    { name: "is_published", label: "Published", type: "toggle" },
  ],
};
