# Generated by Django 6.0.1 on 2026-06-14 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed across all users. Blank = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Percent (1–100) or flat ₹.', max_digits=8),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed')], default='reserved', max_length=10)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='payments.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['coupon', 'status'], name='payments_co_coupon__333d6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'user'), name='uniq_coupon_user_redemption')],
            },
        ),
    ]
